// Container Management Actions
export enum ContainerActionTypes {
  // Container Data Management
  FETCH_CONTAINERS_REQUEST = 'FETCH_CONTAINERS_REQUEST',
  FETCH_CONTAINERS_SUCCESS = 'FETCH_CONTAINERS_SUCCESS',
  FETCH_CONTAINERS_FAILURE = 'FETCH_CONTAINERS_FAILURE',

  // Docker Info Management
  FETCH_DOCKER_INFO_REQUEST = 'FETCH_DOCKER_INFO_REQUEST',
  FETCH_DOCKER_INFO_SUCCESS = 'FETCH_DOCKER_INFO_SUCCESS',
  FETCH_DOCKER_INFO_FAILURE = 'FETCH_DOCKER_INFO_FAILURE',

  // Container Operations
  EXECUTE_CONTAINER_ACTION_REQUEST = 'EXECUTE_CONTAINER_ACTION_REQUEST',
  EXECUTE_CONTAINER_ACTION_SUCCESS = 'EXECUTE_CONTAINER_ACTION_SUCCESS',
  EXECUTE_CONTAINER_ACTION_FAILURE = 'EXECUTE_CONTAINER_ACTION_FAILURE',

  // Container Polling
  START_CONTAINER_POLLING = 'START_CONTAINER_POLLING',
  STOP_CONTAINER_POLLING = 'STOP_CONTAINER_POLLING',
  CONTAINER_POLL_TICK = 'CONTAINER_POLL_TICK',

  // Manual Operations
  REFRESH_CONTAINERS = 'REFRESH_CONTAINERS',
  RESTART_NGINX = 'RESTART_NGINX',

  // Connection Status
  SET_CONNECTION_STATUS = 'SET_CONNECTION_STATUS',
  UPDATE_POLLING_STATUS = 'UPDATE_POLLING_STATUS',
}

// Network Information Actions
export enum NetworkActionTypes {
  FETCH_NETWORK_INFO_REQUEST = 'FETCH_NETWORK_INFO_REQUEST',
  FETCH_NETWORK_INFO_SUCCESS = 'FETCH_NETWORK_INFO_SUCCESS',
  FETCH_NETWORK_INFO_FAILURE = 'FETCH_NETWORK_INFO_FAILURE',
}

// System Actions
export enum SystemActionTypes {
  INITIALIZE_APP = 'INITIALIZE_APP',
  SET_THEME = 'SET_THEME',
  SHOW_NOTIFICATION = 'SHOW_NOTIFICATION',
  HIDE_NOTIFICATION = 'HIDE_NOTIFICATION',
  SET_LOADING = 'SET_LOADING',
  SET_ERROR = 'SET_ERROR',
  CLEAR_ERROR = 'CLEAR_ERROR',
}

// SearXNG Configuration Actions
export enum SearxngActionTypes {
  FETCH_SEARXNG_CONFIG_REQUEST = 'FETCH_SEARXNG_CONFIG_REQUEST',
  FETCH_SEARXNG_CONFIG_SUCCESS = 'FETCH_SEARXNG_CONFIG_SUCCESS',
  FETCH_SEARXNG_CONFIG_FAILURE = 'FETCH_SEARXNG_CONFIG_FAILURE',
  UPDATE_SEARXNG_CONFIG_REQUEST = 'UPDATE_SEARXNG_CONFIG_REQUEST',
  UPDATE_SEARXNG_CONFIG_SUCCESS = 'UPDATE_SEARXNG_CONFIG_SUCCESS',
  UPDATE_SEARXNG_CONFIG_FAILURE = 'UPDATE_SEARXNG_CONFIG_FAILURE',
}

// Combined Action Types
export type AppActionTypes = 
  | ContainerActionTypes
  | NetworkActionTypes
  | SystemActionTypes
  | SearxngActionTypes
