import { Component } from 'react'
import { Download, RotateCcw } from 'lucide-react'

// Generate a cryptographically secure random string for secret keys
function generateRandomString(): string {
  // Try to use crypto.randomUUID if available
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    try {
      return crypto.randomUUID()
    } catch (e) {
      // Fall back to alternative method if crypto.randomUUID fails
    }
  }

  // Fallback method using crypto.getRandomValues if available
  if (typeof crypto !== 'undefined' && crypto.getRandomValues) {
    const array = new Uint8Array(16)
    crypto.getRandomValues(array)
    return Array.from(array, byte => byte.toString(16).padStart(2, '0')).join('')
  }

  // Final fallback using Math.random (less secure but functional)
  return Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2)
}

interface SearXngSettings {
  general: {
    instance_name: string
    contact_url: string
    enable_http: boolean
  }
  search: {
    safe_search: number
    autocomplete: string
    default_lang: string
    ban_time_on_fail: number
    max_ban_time_on_fail: number
  }
  server: {
    port: number
    bind_address: string
    secret_key: string
    base_url: string
    image_proxy: boolean
  }
  ui: {
    default_theme: string
    default_locale: string
    results_on_new_tab: boolean
    infinite_scroll: boolean
  }
  engines: {
    [key: string]: {
      disabled: boolean
      weight: number
    }
  }
}

const defaultSettings: SearXngSettings = {
  general: {
    instance_name: "Privacy Hub Search",
    contact_url: "https://github.com/searxng/searxng",
    enable_http: false
  },
  search: {
    safe_search: 1,
    autocomplete: "google",
    default_lang: "en",
    ban_time_on_fail: 5,
    max_ban_time_on_fail: 120
  },
  server: {
    port: 8080,
    bind_address: "0.0.0.0",
    secret_key: generateRandomString(),
    base_url: "",
    image_proxy: true
  },
  ui: {
    default_theme: "simple",
    default_locale: "en",
    results_on_new_tab: false,
    infinite_scroll: false
  },
  engines: {
    "google": { disabled: false, weight: 1.0 },
    "bing": { disabled: false, weight: 0.8 },
    "duckduckgo": { disabled: false, weight: 1.0 },
    "startpage": { disabled: false, weight: 0.9 },
    "wikipedia": { disabled: false, weight: 1.0 },
    "github": { disabled: false, weight: 0.8 },
    "stackoverflow": { disabled: false, weight: 0.8 },
    "reddit": { disabled: true, weight: 0.7 }
  }
}

interface SearXngConfigState {
  settings: SearXngSettings
  activeTab: 'general' | 'search' | 'server' | 'ui' | 'engines'
}

export class SearXngConfig extends Component<{}, SearXngConfigState> {
  constructor(props: {}) {
    super(props)
    this.state = {
      settings: defaultSettings,
      activeTab: 'general'
    }
  }

  updateSetting = (section: keyof SearXngSettings, key: string, value: any) => {
    this.setState(prev => ({
      settings: {
        ...prev.settings,
        [section]: {
          ...prev.settings[section],
          [key]: value
        }
      }
    }))
  }

  updateEngineSettings = (engine: string, key: 'disabled' | 'weight', value: any) => {
    this.setState(prev => ({
      settings: {
        ...prev.settings,
        engines: {
          ...prev.settings.engines,
          [engine]: {
            ...prev.settings.engines[engine],
            [key]: value
          }
        }
      }
    }))
  }

  setActiveTab = (tab: 'general' | 'search' | 'server' | 'ui' | 'engines') => {
    this.setState({ activeTab: tab })
  }

  generateYamlConfig = () => {
    const { settings } = this.state
    const yamlConfig = `# SearXNG Configuration
# Generated by Privacy Hub Dashboard

general:
  instance_name: "${settings.general.instance_name}"
  contact_url: "${settings.general.contact_url}"
  enable_http: ${settings.general.enable_http}

search:
  safe_search: ${settings.search.safe_search}
  autocomplete: "${settings.search.autocomplete}"
  default_lang: "${settings.search.default_lang}"
  ban_time_on_fail: ${settings.search.ban_time_on_fail}
  max_ban_time_on_fail: ${settings.search.max_ban_time_on_fail}

server:
  port: ${settings.server.port}
  bind_address: "${settings.server.bind_address}"
  secret_key: "${settings.server.secret_key}"
  ${settings.server.base_url ? `base_url: "${settings.server.base_url}"` : '# base_url: ""'}
  image_proxy: ${settings.server.image_proxy}

ui:
  default_theme: "${settings.ui.default_theme}"
  default_locale: "${settings.ui.default_locale}"
  results_on_new_tab: ${settings.ui.results_on_new_tab}
  infinite_scroll: ${settings.ui.infinite_scroll}

engines:
${Object.entries(settings.engines).map(([engine, config]) =>
      `  - name: ${engine}
    disabled: ${config.disabled}
    weight: ${config.weight}`
    ).join('\n')}
`
    return yamlConfig
  }

  downloadConfig = () => {
    const config = this.generateYamlConfig()
    const blob = new Blob([config], { type: 'text/yaml' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'searxng-settings.yml'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  resetToDefaults = () => {
    if (window.confirm('Reset all settings to defaults? This cannot be undone.')) {
      this.setState({ settings: defaultSettings })
    }
  }

  tabClasses = (tab: string) =>
    `px-4 py-2 text-sm font-medium rounded-lg transition-colors ${this.state.activeTab === tab
      ? 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300'
      : 'text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200'
    }`

  render() {
    const { settings, activeTab } = this.state

    return (
      <div className="p-6">
        <p className="text-gray-600 dark:text-gray-400 mb-6">
          Configure your private search engine settings and download the configuration file.
        </p>

        {/* Tab Navigation */}
        <div className="mb-6 border-b border-gray-200 dark:border-gray-700">
          <nav className="flex space-x-2 pb-4">
            {(['general', 'search', 'server', 'ui', 'engines'] as const).map(tab => (
              <button
                type="button"
                key={tab}
                onClick={() => this.setActiveTab(tab)}
                className={this.tabClasses(tab)}
              >
                {tab.charAt(0).toUpperCase() + tab.slice(1)}
              </button>
            ))}
          </nav>
        </div>

        {/* Tab Content */}
        <div className="mb-6">
          {activeTab === 'general' && (
            <div className="space-y-6">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white">General Settings</h3>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Instance Name
                  </label>
                  <input
                    type="text"
                    value={settings.general.instance_name}
                    onChange={(e) => this.updateSetting('general', 'instance_name', e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:text-white"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Contact URL
                  </label>
                  <input
                    type="url"
                    value={settings.general.contact_url}
                    onChange={(e) => this.updateSetting('general', 'contact_url', e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:text-white"
                  />
                </div>
              </div>

              <div className="flex items-center">
                <input
                  type="checkbox"
                  id="enable_http"
                  checked={settings.general.enable_http}
                  onChange={(e) => this.updateSetting('general', 'enable_http', e.target.checked)}
                  className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
                />
                <label htmlFor="enable_http" className="ml-2 text-sm text-gray-700 dark:text-gray-300">
                  Enable HTTP (not recommended for production)
                </label>
              </div>
            </div>
          )}

          {activeTab === 'search' && (
            <div className="space-y-6">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Search Settings</h3>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Safe Search Level
                  </label>
                  <select
                    value={settings.search.safe_search}
                    onChange={(e) => this.updateSetting('search', 'safe_search', parseInt(e.target.value))}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:text-white"
                  >
                    <option value={0}>Off</option>
                    <option value={1}>Moderate</option>
                    <option value={2}>Strict</option>
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Default Language
                  </label>
                  <select
                    value={settings.search.default_lang}
                    onChange={(e) => this.updateSetting('search', 'default_lang', e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:text-white"
                  >
                    <option value="en">English</option>
                    <option value="de">German</option>
                    <option value="fr">French</option>
                    <option value="es">Spanish</option>
                    <option value="it">Italian</option>
                    <option value="pt">Portuguese</option>
                    <option value="ru">Russian</option>
                    <option value="ja">Japanese</option>
                    <option value="zh">Chinese</option>
                  </select>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'engines' && (
            <div className="space-y-6">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Search Engines</h3>

              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {Object.entries(settings.engines).map(([engine, config]) => (
                  <div key={engine} className="border border-gray-200 dark:border-gray-600 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-3">
                      <h4 className="font-medium text-gray-900 dark:text-white capitalize">{engine}</h4>
                      <label className="flex items-center">
                        <input
                          type="checkbox"
                          checked={!config.disabled}
                          onChange={(e) => this.updateEngineSettings(engine, 'disabled', !e.target.checked)}
                          className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
                        />
                        <span className="ml-2 text-sm text-gray-600 dark:text-gray-400">Enabled</span>
                      </label>
                    </div>

                    <div>
                      <label className="block text-sm text-gray-600 dark:text-gray-400 mb-1">
                        Weight: {config.weight}
                      </label>
                      <input
                        type="range"
                        min="0"
                        max="2"
                        step="0.1"
                        value={config.weight}
                        onChange={(e) => this.updateEngineSettings(engine, 'weight', parseFloat(e.target.value))}
                        className="w-full"
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Actions */}
        <div className="pt-6 border-t border-gray-200 dark:border-gray-700 flex justify-between">
          <button
            type="button"
            onClick={this.resetToDefaults}
            className="flex items-center space-x-2 px-4 py-2 text-gray-600 dark:text-gray-400 hover:text-red-600 dark:hover:text-red-400 transition-colors"
          >
            <RotateCcw className="w-4 h-4" />
            <span>Reset to Defaults</span>
          </button>

          <div className="flex space-x-3">
            <button
              type="button"
              onClick={this.downloadConfig}
              className="flex items-center space-x-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
            >
              <Download className="w-4 h-4" />
              <span>Download Config</span>
            </button>
          </div>
        </div>
      </div>
    )
  }
}